spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
    password: HR
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
      
      
      
      
spring:
  application:
    name: actuator-example

info:
  app:
    name: ${spring.application.name}
    author: java
  build:
    artifactId: '@project.artifact@'
    groupId: '@project.groupId@'
    version: '@project.version@'
  java:
    version:@java.version@
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
     
  endpoint:
    health:
      show-details:  always
      
  info:
    env:
      enabled: true
    java:
      enabled: true 